version: '3.8'

services:
  database:
    image: postgres:15-alpine
    env_file:
      - .env.production.local
    container_name: urls-check-database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  api:
    build:
      context: .
      target: production
    env_file:
      - .env.production.local
    container_name: urls-check-api
    depends_on:
      - database
    ports:
      - '${APPLICATION_PORT}:${APPLICATION_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/${POSTGRES_DB}
      - NODE_ENV=production
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    name: urls-check-network
    external: true
